// ===========================================================================
// lib/widgets/quiz_view.dart
// ---------------------------------------------------------------------------
// Shows the quiz for a topic as an interactive set of questions. The quiz was
// generated by the AI and saved as JSON text. This widget reads that JSON,
// shows each question with tappable options, and reveals the correct answer.
// ===========================================================================

import 'dart:convert';
import 'package:flutter/material.dart';

class QuizView extends StatefulWidget {
  // The quiz as JSON text (from the database).
  final String quizJson;
  const QuizView({super.key, required this.quizJson});

  @override
  State<QuizView> createState() => _QuizViewState();
}

class _QuizViewState extends State<QuizView> {
  List<dynamic> _questions = [];
  // Remembers which option the student picked for each question.
  final Map<int, String> _selected = {};
  String? _error;

  @override
  void initState() {
    super.initState();
    // Try to read the JSON. The AI sometimes wraps it in extra text, so we
    // carefully find the list part and ignore the rest.
    try {
      final text = widget.quizJson.trim();
      final start = text.indexOf('[');
      final end = text.lastIndexOf(']');
      if (start != -1 && end != -1) {
        _questions = jsonDecode(text.substring(start, end + 1));
      } else {
        _error = 'Quiz could not be read.';
      }
    } catch (e) {
      _error = 'Quiz could not be read.';
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_error != null) {
      return Center(child: Text(_error!));
    }
    if (_questions.isEmpty) {
      return const Center(child: Text('No quiz available yet.'));
    }

    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: _questions.length,
      itemBuilder: (context, qIndex) {
        final q = _questions[qIndex] as Map<String, dynamic>;
        final question = q['question'] ?? '';
        final options = List<String>.from(q['options'] ?? []);
        final correct = q['answer'] ?? '';
        final picked = _selected[qIndex];

        return Card(
          margin: const EdgeInsets.only(bottom: 16),
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('${qIndex + 1}. $question',
                    style: const TextStyle(fontWeight: FontWeight.bold)),
                const SizedBox(height: 8),
                // One tappable row per option.
                ...options.map((option) {
                  // Decide the color: green if correct (after picking),
                  // red if it's the wrong one the student picked.
                  Color? color;
                  if (picked != null) {
                    if (option == correct) {
                      color = Colors.green.shade100;
                    } else if (option == picked) {
                      color = Colors.red.shade100;
                    }
                  }
                  return Container(
                    margin: const EdgeInsets.symmetric(vertical: 4),
                    decoration: BoxDecoration(
                      color: color,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: ListTile(
                      title: Text(option),
                      // Once answered, don't allow changing it.
                      onTap: picked != null
                          ? null
                          : () => setState(() => _selected[qIndex] = option),
                    ),
                  );
                }),
              ],
            ),
          ),
        );
      },
    );
  }
}
